import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const html = readFileSync(new URL("../瀚纳仕H5 demo-启动舱.html", import.meta.url), "utf8");
const legacy = readFileSync(new URL("../瀚纳仕H5 demo.html", import.meta.url), "utf8");

assert.match(html, /<title>今天的班，先让 AI 起一卦<\/title>/);
assert.doesNotMatch(html, /<title>AI 打工命盘 H5 线稿<\/title>/);

[
  ["formScreen", "form-ritual-screen"],
  ["questionScreen", "question-ritual-screen"],
  ["loadingScreen", "loading-ritual-screen"],
  ["reportScreen", "report-ritual-screen"],
  ["posterScreen", "poster-ritual-screen"]
].forEach(([id, className]) => {
  assert.match(html, new RegExp(`<section class="screen ritual-screen ${className}" id="${id}">`));
});

assert.match(html, /<div class="global-brand-dock">/);
assert.match(html, /<button class="music-toggle global-music-toggle" id="musicToggle" type="button" aria-label="关闭音乐" aria-pressed="true">/);
assert.doesNotMatch(html, /<button class="music-toggle global-music-toggle is-muted" id="musicToggle"/);
assert.match(html, /\.music-toggle \{\n[\s\S]*?width: 42px;[\s\S]*?height: 42px;/);
assert.match(html, /\.music-toggle \{\n[\s\S]*?-webkit-tap-highlight-color: rgba\(0, 0, 0, 0\);[\s\S]*?-webkit-touch-callout: none;[\s\S]*?touch-action: manipulation;[\s\S]*?overflow: hidden;[\s\S]*?outline: none;/);
assert.match(html, /\.music-toggle \*,\n    \.music-toggle::before,\n    \.music-toggle::after \{\n[\s\S]*?-webkit-tap-highlight-color: rgba\(0, 0, 0, 0\);/);
assert.match(html, /\.music-toggle:focus,\n    \.music-toggle:focus-visible,\n    \.music-toggle:active \{\n[\s\S]*?outline: none;/);
assert.match(html, /function toggleMusic\(\) \{\n\s+musicToggle\.blur\(\);/);
assert.match(html, /\.music-glyph \{\n[\s\S]*?font-size: 29px;/);
assert.equal(existsSync(new URL("../assets/audio/cyberpunk-549451.mp3", import.meta.url)), true, "BGM asset should exist");
assert.match(html, /<source src="assets\/audio\/cyberpunk-549451\.mp3" type="audio\/mpeg">/);
assert.match(html, /const MUSIC_VOLUME = 0\.42;/);
assert.match(html, /const SFX_VOLUME = 0\.26;/);
assert.match(html, /let isMusicOn = true;/);
assert.match(html, /function primeDefaultMusic\(\)/);
assert.match(html, /function unlockAudio\(\)/);
assert.match(html, /function playMusic\(\)/);
assert.match(html, /function playTone\(/);
assert.match(html, /function playSweep\(/);
assert.match(html, /function playSfx\(type\)/);
["power", "tap", "select", "flip", "scan", "reveal", "poster", "share", "save"].forEach(effect => {
  assert.match(html, new RegExp(`${effect}: \\(\\) =>|playSfx\\("${effect}"\\)`), `${effect} sfx should be wired`);
});
assert.match(html, /<div class="ritual-page-shell">/);
assert.match(html, /<div class="ritual-step-orbit" aria-hidden="true">/);
assert.match(html, /<div class="loading-oracle-core" aria-hidden="true">/);
assert.doesNotMatch(html, /<div class="loading-steps"/);
assert.doesNotMatch(html, /class="loading-step"/);
assert.doesNotMatch(html, />生成报告<\/div>/);
assert.match(html, /<div class="poster-aura" aria-hidden="true">/);
assert.match(html, /<div class="poster-scene" aria-hidden="true">/);
assert.match(html, /id="posterSceneLaptop"/);
assert.match(html, /id="posterSceneBadge"/);
assert.match(html, /id="posterSceneDoor"/);
assert.match(html, /id="posterSceneArrow"/);
assert.match(html, /<canvas class="qr-wire" id="posterQrCanvas" width="240" height="240" aria-label="H5 页面二维码"><\/canvas>/);
assert.match(html, /<img class="poster-save-image" id="posterSaveImage" alt="可长按保存的海报">/);
assert.doesNotMatch(html, /assets\/hays-qr\.png/);
assert.match(html, /<script src="assets\/qrcode\.min\.js"><\/script>/);
assert.equal(existsSync(new URL("../assets/qrcode.min.js", import.meta.url)), true, "local QR library should exist");
assert.doesNotMatch(html, /cdn\.jsdelivr\.net\/npm\/qrcode/);
assert.doesNotMatch(html, /二维码占位/);
["form-bg.png", "question-bg.png", "loading-bg.png", "report-bg.png", "poster-bg.png"].forEach(asset => {
  assert.equal(existsSync(new URL(`../assets/${asset}`, import.meta.url)), true, `${asset} should exist`);
  assert.match(html, new RegExp(`assets/${asset}`));
});
["fate-money.png", "fate-ally.png", "fate-chance.png", "fate-offer.png", "fate-retrograde.png", "fate-switch.png"].forEach(asset => {
  assert.equal(existsSync(new URL(`../assets/${asset}`, import.meta.url)), true, `${asset} should exist`);
  assert.match(html, new RegExp(`assets/${asset}`));
});
const ritualBackgroundBlock = html.match(/\.ritual-screen::before \{([\s\S]*?)\n    \}/)?.[1] || "";
const posterCardBlock = html.match(/\.poster-card \{([\s\S]*?)\n    \}/)?.[1] || "";
assert.doesNotMatch(ritualBackgroundBlock, /assets\/home-bg\.png/);
assert.doesNotMatch(posterCardBlock, /assets\/home-bg\.png/);
assert.match(html, /<span class="fate-visual fate-visual--money" aria-hidden="true">/);
assert.match(html, /<span class="fate-visual fate-visual--ally" aria-hidden="true">/);
assert.match(html, /<span class="fate-visual fate-visual--chance" aria-hidden="true">/);
assert.match(html, /<span class="fate-visual fate-visual--offer" aria-hidden="true">/);
assert.match(html, /<span class="fate-visual fate-visual--retrograde" aria-hidden="true">/);
assert.match(html, /<span class="fate-visual fate-visual--switch" aria-hidden="true">/);
assert.match(html, /<span class="fate-copy">钱来不来<\/span>/);
assert.doesNotMatch(html, /background-image: url\("assets\/fate-card-sprite\.png"\);/);
assert.match(html, /\.fate-visual--money \{ background-image: url\("assets\/fate-money\.png"\); \}/);
assert.match(html, /\.fate-visual--offer \{ background-image: url\("assets\/fate-offer\.png"\); \}/);
const fateVisualBlock = html.match(/\.fate-visual \{([\s\S]*?)\n    \}/)?.[1] || "";
assert.match(fateVisualBlock, /position: absolute;/);
assert.match(fateVisualBlock, /inset: 0;/);
assert.match(fateVisualBlock, /width: 100%;/);
assert.match(fateVisualBlock, /height: 100%;/);
assert.match(fateVisualBlock, /background-size: cover;/);
assert.match(fateVisualBlock, /mix-blend-mode: screen;/);
assert.doesNotMatch(fateVisualBlock, /border:/);
assert.doesNotMatch(fateVisualBlock, /border-radius:\s*20px/);
assert.match(html, /\.fate-card\.is-selected \{\n[\s\S]*?outline: 2px solid rgba\(200, 251, 232, \.9\);/);
assert.match(html, /\.ritual-screen \.date-input \{/);
assert.match(html, /-webkit-appearance: none;/);
assert.match(html, /background-position: calc\(100% - 26px\) 50%, calc\(100% - 18px\) 50%, 0 0;/);
assert.match(html, /\.ritual-screen::before/);
assert.match(html, /\.ritual-screen::after/);
assert.match(html, /\.ritual-screen \.section-card/);
assert.match(html, /\.ritual-screen \.option-btn\.is-selected/);
assert.match(html, /\.report-title-block::before/);
assert.match(html, /\.report-ritual-screen \.nav-line \{\n[\s\S]*?justify-content: flex-start;/);
assert.match(html, /\.poster-card::before/);
assert.match(html, /@keyframes ritualBgDrift/);
assert.match(html, /@keyframes ritualSweep/);
assert.match(html, /@keyframes oracleSpin/);
assert.match(html, /@keyframes posterAura/);
assert.match(html, /<div class="share-guide" id="shareGuide" aria-hidden="true">/);
assert.doesNotMatch(html, /把这张工牌甩进群/);
assert.doesNotMatch(html, /收到，去摇人/);
assert.doesNotMatch(html, /id="shareGuideClose"/);
assert.doesNotMatch(html, /\.share-guide-close/);
assert.doesNotMatch(html, /shareGuideClose/);
assert.match(html, /<div class="poster-qr-block">/);
assert.match(html, /扫码给自己也起一卦/);
assert.doesNotMatch(html, /poster-qr-divider/);
assert.doesNotMatch(html, /机会不是没来，是正在等你把入口打开。/);
assert.match(html, /\.share-guide\.is-visible/);
assert.match(html, /@keyframes shareArrowFloat/);
assert.match(html, /function openShareGuide\(\)/);
assert.match(html, /分享好友[\s\S]*openShareGuide\(\);/);
assert.match(html, /data-long-press-save="poster"/);
assert.equal(existsSync(new URL("../assets/poster-result-template.png", import.meta.url)), true, "poster template image should exist");
assert.match(html, /\.poster-card \{\n[\s\S]*?min-height: 960px;[\s\S]*?grid-template-rows: auto;[\s\S]*?border: 1px solid rgba\(200, 251, 232, \.52\);[\s\S]*?border-radius: 28px;/);
assert.match(html, /\.poster-qr-block \{\n[\s\S]*?grid-template-columns: 1fr;[\s\S]*?justify-items: center;/);
assert.doesNotMatch(html, /\.poster-qr-block::before/);
assert.match(html, /\.poster-qr-copy \{\n[\s\S]*?font-size: 18px;[\s\S]*?text-align: center;/);
assert.match(html, /<div class="qr-crop">\s*<canvas class="qr-wire" id="posterQrCanvas" width="240" height="240" aria-label="H5 页面二维码"><\/canvas>\s*<\/div>/);
assert.match(html, /\.qr-crop \{\n[\s\S]*?overflow: hidden;/);
assert.match(html, /\.poster-scene \{\n[\s\S]*?height: 288px;[\s\S]*?margin: 24px auto 12px;/);
assert.match(html, /\.poster-metric-list,\n    \.poster-risk \{\n[\s\S]*?display: none;/);
assert.match(html, /\.poster-save-image \{\n[\s\S]*?-webkit-touch-callout: default;/);
assert.match(html, /\.poster-save-image \{\n[\s\S]*?pointer-events: auto;/);
assert.match(html, /\.poster-board\.is-save-ready \{\n[\s\S]*?touch-action: auto;[\s\S]*?-webkit-user-select: auto;/);
assert.doesNotMatch(html, /poster-save-tip/);
assert.doesNotMatch(html, /长按点亮保存姿势/);
assert.match(html, /长按海报图片保存到相册/);
assert.match(html, /function getH5ShareUrl\(\)/);
assert.match(html, /function renderPosterQr\(\)/);
assert.match(html, /const shareUrl = getH5ShareUrl\(\);/);
assert.match(html, /function renderPosterQrWithQRCodeJs\(shareUrl\)/);
assert.match(html, /new QRCode\(holder,/);
assert.doesNotMatch(html, /function drawFallbackQr/);
assert.match(html, /function renderPosterImage\(report\)/);
assert.match(html, /const POSTER_TEMPLATE_SRC = "assets\/poster-result-template\.png";/);
assert.match(html, /posterTemplateImage\.src = POSTER_TEMPLATE_SRC;/);
assert.match(html, /drawPosterTemplate\(context, width, height\);/);
assert.match(html, /drawPosterLogo\(context, 48, 48, 156, 39\);/);
assert.match(html, /function drawPosterTemplate\(context, width, height\)/);
assert.match(html, /function getPosterScene\(report = \{\}\)/);
assert.match(html, /function renderPosterScene\(report\)/);
assert.match(html, /function drawPosterScene\(context, scene, x, y, width, height\)/);
assert.doesNotMatch(html, /drawPosterScene\(context, scene, 44, 126, width - 88, 246\);/);
assert.match(html, /function drawPosterInsightBox\(context, text, x, y, width, height\)/);
assert.match(html, /function drawPosterResultPanel\(context, report, action, x, y, width, height\)/);
assert.match(html, /function drawPosterQrCta\(context, width, height\)/);
assert.match(html, /context\.fillText\("扫码给自己也起一卦"/);
assert.match(html, /context\.fillText\("扫码给自己也起一卦", width \/ 2,/);
assert.doesNotMatch(html, /context\.fillText\("机会不是没来，是正在等你把入口打开。"/);
const renderPosterImageBlock = html.match(/function renderPosterImage\(report\) \{([\s\S]*?)\n    \}/)?.[1] || "";
assert.doesNotMatch(renderPosterImageBlock, /drawRatingPill/);
assert.doesNotMatch(renderPosterImageBlock, /水逆提醒/);
assert.match(html, /posterSaveImage\.src = canvas\.toDataURL\("image\/png"\);/);
assert.match(html, /posterArea\.classList\.add\("is-save-ready"\);/);
assert.doesNotMatch(html, /context\.fillText\("长按保存海报"/);
assert.match(html, /const LONG_PRESS_MS = 650;/);
assert.match(html, /function startPosterPress\(event\)/);
assert.match(html, /posterArea\.classList\.contains\("is-save-ready"\) && event\.target === posterSaveImage/);
assert.match(html, /function cancelPosterPress/);
assert.match(html, /\.persona-user-name/);
assert.match(html, /function escapeHTML/);
assert.match(html, /personaSubline\.innerHTML/);
assert.match(html, /\.ritual-screen \.index-row \{/);
assert.match(html, /grid-template-areas:\n        "label stars"\n        "track track";/);
assert.match(html, /\.loading-ritual-screen::before/);
const ritualSectionLabelBlock = html.match(/\.ritual-screen \.section-label,\n    \.ritual-screen \.draw-title \{([\s\S]*?)\n    \}/)?.[1] || "";
assert.match(ritualSectionLabelBlock, /color: #c8fbe8;/);
assert.match(ritualSectionLabelBlock, /text-shadow: 0 0 14px rgba\(160, 242, 228, \.34\);/);
assert.doesNotMatch(legacy, /ritual-screen/);
